### ISSUE TITLE
check builds with multiple compilers

### ISSUE THREAD

**Issue by SingingBush** [nomad-software/dunit#16]
please consider updating your `.travis.yml` to ensure that the project will work with various os/compiler combinations.

```yml
language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - ldc
  - gdc

os:
  - linux
  - osx
```
